CREATE TABLE `lowcode_bookmark_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `category` varchar(32) DEFAULT NULL COMMENT '分类',
  `center` varchar(32) DEFAULT NULL COMMENT '中心',
  `name` varchar(255) DEFAULT NULL COMMENT '书签名字',
  `link` varchar(255) DEFAULT NULL COMMENT '书签地址',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_flag` tinyint(1) DEFAULT '0' COMMENT '删除标识-0: 未删除 1-已删除',
  `create_user` varchar(32) DEFAULT NULL COMMENT '创建人',
  `update_user` varchar(32) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`),
  KEY `idx_name` (`name`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='常用链接地址';

CREATE TABLE `lowcode_code_day_stat_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `download_times` int(11) DEFAULT NULL COMMENT '使用(下载)次数',
  `code_total_num` bigint(20) DEFAULT NULL COMMENT '代码生产量(行)',
  `user_num` int(11) DEFAULT NULL COMMENT '用户数',
  `active_user_num` int(11) DEFAULT NULL COMMENT '活跃用户数',
  `use_system_num` int(11) DEFAULT NULL COMMENT '接入系统数',
  `tool_method_num` int(11) DEFAULT NULL COMMENT '工具方法数',
  `database_num` int(11) DEFAULT NULL COMMENT '数据库数',
  `tables_num` int(11) DEFAULT NULL COMMENT '数据库表数量',
  `start_date` datetime DEFAULT NULL COMMENT '开始时间',
  `end_date` datetime DEFAULT NULL COMMENT '结束时间',
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_flag` tinyint(1) DEFAULT '0' COMMENT '删除标识-0: 未删除 1-已删除',
  `create_user` varchar(255) DEFAULT NULL COMMENT '创建人',
  `update_user` varchar(255) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='代码-日统计表';
CREATE TABLE `lowcode_code_gen_base_config` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `author_name` varchar(255) NOT NULL COMMENT '作者姓名',
  `class_name` varchar(255) NOT NULL COMMENT '类名',
  `table_prefix` varchar(255) NOT NULL DEFAULT '' COMMENT '是否移除表前缀',
  `generate_type` varchar(255) NOT NULL DEFAULT '' COMMENT '生成位置类型',
  `table_name` varchar(255) NOT NULL COMMENT '数据库表名',
  `package_name` varchar(255) DEFAULT NULL COMMENT '包名称',
  `bus_name` varchar(255) DEFAULT NULL COMMENT '业务名',
  `child_bus_name` varchar(255) NOT NULL DEFAULT '',
  `table_comment` varchar(255) DEFAULT NULL COMMENT '功能名',
  `create_user` bigint(20) DEFAULT NULL COMMENT '创建人',
  `create_date` datetime DEFAULT NULL COMMENT '创建时间',
  `update_user` bigint(20) DEFAULT NULL COMMENT '更新人',
  `update_date` datetime DEFAULT NULL COMMENT '更新时间',
  `delete_flag` tinyint(4) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='代码生成基础配置';
CREATE TABLE `lowcode_code_gen_detail_config` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `code_gen_id` bigint(20) DEFAULT NULL COMMENT '代码生成主表ID',
  `column_name` varchar(255) DEFAULT NULL COMMENT '数据库字段名',
  `java_name` varchar(255) DEFAULT NULL COMMENT 'java类字段名',
  `data_type` varchar(255) DEFAULT NULL COMMENT '物理类型',
  `column_comment` varchar(255) DEFAULT NULL COMMENT '字段描述',
  `java_type` varchar(255) DEFAULT NULL COMMENT 'java类型',
  `effect_type` varchar(255) DEFAULT NULL COMMENT '作用类型（字典）',
  `dict_type_code` varchar(255) DEFAULT NULL COMMENT '字典code',
  `whether_table` varchar(255) DEFAULT NULL COMMENT '列表展示',
  `whether_add_update` varchar(255) DEFAULT NULL COMMENT '增改',
  `whether_retract` varchar(255) DEFAULT NULL COMMENT '列表是否缩进（字典）',
  `whether_required` varchar(255) DEFAULT NULL COMMENT '是否必填（字典）',
  `query_whether` varchar(255) DEFAULT NULL COMMENT '是否是查询条件',
  `query_type` varchar(255) DEFAULT NULL COMMENT '查询方式',
  `column_key` varchar(255) DEFAULT NULL COMMENT '主键',
  `column_key_name` varchar(255) DEFAULT NULL COMMENT '主外键名称',
  `whether_common` varchar(255) DEFAULT NULL COMMENT '是否是通用字段',
  `create_date` datetime DEFAULT NULL COMMENT '创建时间',
  `create_user` bigint(20) DEFAULT NULL COMMENT '创建人',
  `update_date` datetime DEFAULT NULL COMMENT '修改时间',
  `update_user` bigint(20) DEFAULT NULL COMMENT '修改人',
  `delete_flag` tinyint(4) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='代码生成详细配置';
CREATE TABLE `lowcode_code_gen_user_db` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id` varchar(40) NOT NULL COMMENT '所属用户id',
  `db_code` varchar(40) NOT NULL COMMENT '数据库标识code',
  `db_driver` varchar(50) NOT NULL COMMENT '数据库驱动类型',
  `db_host` varchar(100) NOT NULL COMMENT '数据库host',
  `db_port` varchar(100) NOT NULL COMMENT '数据库port',
  `db_url` varchar(500) NOT NULL COMMENT '数据库连接url',
  `db_username` varchar(100) NOT NULL COMMENT '账户',
  `db_password` varchar(100) NOT NULL COMMENT '密码',
  `db_name` varchar(100) NOT NULL COMMENT '数据库名',
  `db_desc` varchar(200) NOT NULL COMMENT '数据库描述用于展示',
  `create_user` varchar(40) NOT NULL DEFAULT 'SYSTEM' COMMENT '创建人',
  `create_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_user` varchar(40) NOT NULL DEFAULT 'SYSTEM' COMMENT '更新人',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_cgud_dc` (`db_code`),
  KEY `idx_cgud_dbname` (`db_name`),
  KEY `idx_cgud_uid` (`user_id`),
  KEY `idx_cgud_dhost` (`db_host`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPACT COMMENT='代码生成所有db连接信息';
CREATE TABLE `lowcode_code_person_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `rank` int(11) DEFAULT '0' COMMENT '排名',
  `access_times` int(11) DEFAULT '0' COMMENT '访问次数',
  `download_times` int(11) DEFAULT '0' COMMENT '下载次数',
  `code_total_num` bigint(20) DEFAULT '0' COMMENT '代码生产量(行)',
  `tool_method_num` int(11) DEFAULT '0' COMMENT '方法数',
  `database_num` int(11) DEFAULT '0' COMMENT '数据库数',
  `tables_num` int(11) DEFAULT '0' COMMENT '数据库表数量',
  `system_code` varchar(50) DEFAULT NULL COMMENT '系统编码',
  `system_name` varchar(100) DEFAULT NULL COMMENT '描述',
  `username` varchar(50) DEFAULT NULL COMMENT '用户名',
  `emp_no` varchar(50) DEFAULT NULL COMMENT '工号',
  `user_org` varchar(50) DEFAULT NULL COMMENT '所属团队',
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP,
  `delete_flag` tinyint(1) DEFAULT '0' COMMENT '删除标识-0: 未删除 1-已删除',
  `create_user` varchar(255) DEFAULT NULL COMMENT '创建人',
  `update_user` varchar(255) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='工作台个人信息';
CREATE TABLE `lowcode_es_mgr` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` varchar(200) DEFAULT NULL COMMENT '名称',
  `cluster_name` varchar(200) DEFAULT NULL COMMENT '集群名',
  `es_addr` varchar(1000) DEFAULT NULL COMMENT 'es地址',
  `remark` varchar(1000) DEFAULT NULL COMMENT '备注',
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `delete_flag` tinyint(1) DEFAULT '0' COMMENT '删除标识-0: 未删除 1-已删除',
  `create_user` varchar(255) DEFAULT NULL COMMENT '创建人',
  `update_user` varchar(255) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`),
  KEY `IDX_PROPERTIES_name` (`name`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ES连接信息管理';
CREATE TABLE `lowcode_function_gen_sql` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `scaffold_gen_info_id` bigint(20) DEFAULT NULL COMMENT '脚手架工程生成-基础信息Id',
  `result_columns` varchar(2048) DEFAULT NULL COMMENT '结果集',
  `relevance_columns` varchar(1024) DEFAULT NULL COMMENT '关联字段',
  `preview_sql` varchar(4000) DEFAULT NULL COMMENT '预览sql',
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_flag` tinyint(1) DEFAULT '0' COMMENT '删除标识-0: 未删除 1-已删除',
  `create_user` varchar(255) DEFAULT NULL COMMENT '创建人',
  `update_user` varchar(255) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='单功能sql预览';

CREATE TABLE `lowcode_gen_file_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `gen_info_id` bigint(20) NOT NULL COMMENT '关联生成主表gen_info的id',
  `gen_db_id` bigint(20) DEFAULT NULL COMMENT '关联gen_db_info表id用于预览获取数据库信息',
  `gen_db_example_id` bigint(20) DEFAULT NULL COMMENT '关联表gen_db_example_info主键id',
  `file_path_name` varchar(512) NOT NULL COMMENT '原始文件路径未替换',
  `real_path_name` varchar(512) NOT NULL COMMENT '替换后的文件路径',
  `method_list_extra` varchar(512) DEFAULT '' COMMENT '文件类包含的方法列表',
  `class_name` varchar(100) DEFAULT NULL COMMENT '文件及类名用于重命名',
  `create_user` varchar(40) NOT NULL DEFAULT 'SYSTEM' COMMENT '创建人',
  `create_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_user` varchar(40) NOT NULL DEFAULT 'SYSTEM' COMMENT '更新人',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  KEY `idx_gfi_gid` (`gen_info_id`),
  KEY `idx_gfi_gdeid` (`gen_db_example_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPACT COMMENT='系统DB信息管理';
CREATE TABLE `lowcode_gen_file_rename_extra` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `gen_info_id` bigint(20) NOT NULL COMMENT '关联生成主表gen_info的id',
  `gen_db_id` bigint(20) NOT NULL COMMENT '关联表gen_db_info主键id',
  `gen_db_example_id` bigint(20) NOT NULL COMMENT '关联表gen_db_example_info主键id',
  `rename_extra` varchar(500) NOT NULL COMMENT '固定好所有的文件名默认先用classname',
  `create_user` varchar(40) NOT NULL DEFAULT 'SYSTEM' COMMENT '创建人',
  `create_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_user` varchar(40) NOT NULL DEFAULT 'SYSTEM' COMMENT '更新人',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  KEY `uniq_gfr_ideid` (`gen_info_id`,`gen_db_id`,`gen_db_example_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPACT COMMENT='文件重命名扩展';
CREATE TABLE `lowcode_gen_log` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `code_total_num` bigint(20) DEFAULT NULL COMMENT '代码生产量(行)',
  `tool_method_num` int(11) DEFAULT NULL COMMENT '方法数',
  `database_name` varchar(200) DEFAULT NULL COMMENT '所有库名',
  `table_name` varchar(200) DEFAULT NULL COMMENT '所有表名',
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `delete_flag` tinyint(1) DEFAULT '0' COMMENT '删除标识-0: 未删除 1-已删除',
  `create_user` varchar(255) DEFAULT NULL COMMENT '创建人',
  `update_user` varchar(255) DEFAULT NULL COMMENT '更新人',
  `system_code` varchar(50) DEFAULT NULL COMMENT '系统编码',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='统计生成代码记录';
CREATE TABLE `lowcode_kafka_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `kafka_name` varchar(255) DEFAULT NULL COMMENT 'kafka名字',
  `cluster_name` varchar(64) DEFAULT NULL COMMENT '集群名字',
  `monitor_url` varchar(255) DEFAULT NULL COMMENT 'monitor地址',
  `consumer_name` varchar(64) DEFAULT NULL COMMENT '消费者名称',
  `check_code` varchar(16) DEFAULT NULL COMMENT '验证码',
  `topic_name` varchar(64) DEFAULT NULL COMMENT 'topic名字',
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_user` varchar(255) DEFAULT NULL COMMENT '创建人',
  `delete_flag` tinyint(1) DEFAULT '0' COMMENT '删除标识-0: 未删除 1-已删除',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `update_user` varchar(255) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='代码生成-kafka配置信息表';
CREATE TABLE `lowcode_mongodb_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `mongodb_name` varchar(255) DEFAULT NULL COMMENT 'mongodb名字',
  `mongodb_database` varchar(64) DEFAULT NULL COMMENT 'mongodb数据库',
  `mongodb_url` varchar(255) DEFAULT NULL COMMENT 'mongodb服务器地址',
  `mongodb_username` varchar(64) DEFAULT NULL COMMENT 'mongodb用户名',
  `mongodb_password` varchar(64) DEFAULT NULL COMMENT 'mongodb密码',
  `mongodb_host` varchar(255) DEFAULT NULL COMMENT 'mongodb host',
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_user` varchar(255) DEFAULT NULL COMMENT '创建人',
  `delete_flag` tinyint(1) DEFAULT '0' COMMENT '删除标识-0: 未删除 1-已删除',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `update_user` varchar(255) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='代码生成-mongodb配置信息表';
CREATE TABLE `lowcode_plugins_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `plugins_code` varchar(20) DEFAULT NULL COMMENT '中间件代号kafka,redis',
  `plugins_name` varchar(30) DEFAULT NULL COMMENT '中间件名称,eg：活动测试环境redis',
  `type` varchar(30) DEFAULT NULL COMMENT '部署方式：例如redis区分sentinel和redis cluster',
  `config_details` varchar(2000) DEFAULT NULL COMMENT '中间件的配置信息',
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `delete_flag` tinyint(1) DEFAULT '0' COMMENT '删除标识-0: 未删除 1-已删除',
  `create_user` varchar(255) DEFAULT NULL COMMENT '创建人',
  `update_user` varchar(255) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='插件信息列表';
CREATE TABLE `lowcode_redis_info` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键，自增长',
  `install_type` varchar(50) DEFAULT NULL COMMENT '部署方式:sentinel或cluster',
  `name` varchar(100) DEFAULT NULL COMMENT '名称',
  `cluster_name` varchar(100) DEFAULT NULL COMMENT '集群名',
  `connect_info` varchar(1024) DEFAULT NULL COMMENT '连接信息',
  `time_out` int(8) DEFAULT '0' COMMENT '超时时间，默认0-表示永不过期',
  `password` varchar(200) DEFAULT NULL COMMENT '密码',
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `delete_flag` tinyint(1) DEFAULT '0' COMMENT '删除标识-0: 未删除 1-已删除',
  `create_user` varchar(255) DEFAULT NULL COMMENT '创建人',
  `update_user` varchar(255) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='Redis信息管理';
CREATE TABLE `lowcode_scaffold_gen_db_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `system_db_id` bigint(20) DEFAULT NULL COMMENT 'systemDB的主键',
  `scaffold_gen_info_id` bigint(20) DEFAULT NULL COMMENT '脚手架工程生成-基础信息Id',
  `driver_class` varchar(255) DEFAULT NULL COMMENT '数据库驱动类型,例如mysql',
  `ip_port` varchar(255) DEFAULT NULL COMMENT 'ip/端口',
  `db_name` varchar(50) DEFAULT NULL COMMENT '数据库名',
  `user_name` varchar(50) DEFAULT NULL COMMENT '用户名',
  `password` varchar(255) DEFAULT NULL COMMENT '密码',
  `primary_db` tinyint(1) DEFAULT '1' COMMENT '是否主库(0-否 1-是)',
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_user` varchar(255) DEFAULT 'SYSTEM' COMMENT '创建人',
  `delete_flag` tinyint(1) DEFAULT '0' COMMENT '删除标识-0: 未删除 1-已删除',
  `update_user` varchar(255) DEFAULT 'SYSTEM' COMMENT '更新人',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='代码生成-数据库关联信息表';
CREATE TABLE `lowcode_scaffold_gen_db_table_detail_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `scaffold_gen_info_id` bigint(20) DEFAULT NULL COMMENT '脚手架工程生成-基础信息Id',
  `sys_dict_id` bigint(20) DEFAULT NULL COMMENT '数据字典id',
  `column_name` varchar(128) DEFAULT NULL COMMENT '数据库字段名',
  `data_type` varchar(16) DEFAULT NULL COMMENT '数据库中类型',
  `column_key` varchar(16) DEFAULT NULL COMMENT '主外键',
  `java_columns` varchar(64) DEFAULT NULL COMMENT 'java字段',
  `java_type` varchar(16) DEFAULT NULL COMMENT 'java类型',
  `column_comment` varchar(255) DEFAULT NULL COMMENT '字段描述',
  `column_key_name` varchar(128) DEFAULT NULL COMMENT '首字母大写名称',
  `show_type` varchar(16) DEFAULT NULL COMMENT '显示类型',
  `query_list_show` tinyint(1) DEFAULT '0' COMMENT '是否在查询列表显示 0:否 1:是',
  `query_list_no` int(11) DEFAULT NULL COMMENT '查询列表显示的顺序号',
  `query_condition` tinyint(1) DEFAULT '0' COMMENT '是否查询条件 0:否 1:是',
  `query_condition_no` int(11) DEFAULT NULL COMMENT '查询条件显示的顺序号',
  `query_condition_like` tinyint(1) DEFAULT '0' COMMENT '查询字段是否模糊 0:否 1:是',
  `show_add_update` tinyint(1) DEFAULT '0' COMMENT '是否在增/改页面显示 0:否 1:是',
  `add_update_no` int(11) DEFAULT NULL COMMENT '增/改页面显示的顺序号',
  `add_update_require` tinyint(1) DEFAULT '0' COMMENT '增/改页面是否必填 0:否 1:是',
  `add_update_validate_tips` varchar(255) DEFAULT '0' COMMENT '增/改页面必填提示的内容',
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_user` varchar(255) DEFAULT NULL COMMENT '创建人',
  `delete_flag` tinyint(1) DEFAULT '0' COMMENT '删除标识-0: 未删除 1-已删除',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `update_user` varchar(255) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`),
  KEY `idx_gen_id` (`scaffold_gen_info_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='代码生成-表关联字段信息表';
CREATE TABLE `lowcode_scaffold_gen_db_table_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `scaffold_gen_db_info_id` bigint(20) DEFAULT NULL COMMENT '脚手架工程生成-数据库信息Id',
  `table_name` varchar(255) DEFAULT NULL COMMENT '表名',
  `table_desc` varchar(255) DEFAULT NULL COMMENT '表描述',
  `class_name` varchar(255) DEFAULT NULL COMMENT '类名',
  `catalog` varchar(255) DEFAULT NULL COMMENT '实例目录名',
  `package_name` varchar(255) DEFAULT NULL COMMENT '包名',
  `author` varchar(255) DEFAULT NULL COMMENT '作者',
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_user` varchar(255) DEFAULT 'SYSTEM' COMMENT '创建人',
  `delete_flag` tinyint(1) DEFAULT '0' COMMENT '删除标识-0: 未删除 1-已删除',
  `update_user` varchar(255) DEFAULT 'SYSTEM' COMMENT '更新人',
  PRIMARY KEY (`id`),
  KEY `idx_gen_db_id` (`scaffold_gen_db_info_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='代码生成-表关联信息表';

CREATE TABLE `lowcode_scaffold_gen_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `scaffold_type` tinyint(1) DEFAULT '2' COMMENT '1: 脚手架工程生成 2: 单功能生成',
  `system_info_id` bigint(20) DEFAULT NULL COMMENT '接入工程id',
  `system_code` varchar(50) DEFAULT NULL COMMENT '系统编码',
  `system_name` varchar(128) DEFAULT NULL COMMENT '系统名称',
  `group_id` varchar(128) DEFAULT NULL COMMENT '工程的groupId',
  `context_path` varchar(20) DEFAULT NULL COMMENT '访问路径',
  `artifact_id` varchar(128) DEFAULT NULL COMMENT '工程的artifactId',
  `version_no` varchar(50) DEFAULT NULL COMMENT '版本号',
  `project_package_name` varchar(128) DEFAULT NULL COMMENT '工程包名',
  `code_lines` int(11) DEFAULT NULL COMMENT '产生代码行',
  `tpl_info_id` bigint(20) DEFAULT NULL COMMENT '模板Id',
  `template_type` tinyint(1) DEFAULT NULL COMMENT '模板类型 1.应用层；2.微服务层；3.前端',
  `gen_functions` varchar(128) DEFAULT NULL COMMENT '生成功能',
  `middleware` varchar(128) DEFAULT NULL COMMENT '中间件(多个使用#分隔),比如redis、kafka',
  `function_collect` varchar(128) DEFAULT NULL COMMENT '功能集合',
  `dir_names` varchar(128) DEFAULT NULL COMMENT '目录名称(多个使用#分隔),比如service、manager、repository',
  `kafka_id` varchar(256) DEFAULT NULL COMMENT 'kafka配置表id',
  `sentinel_id` bigint(20) DEFAULT NULL COMMENT 'sentinel配置表id',
  `es_id` bigint(20) DEFAULT NULL COMMENT 'es配置表id',
  `mongodb_id` bigint(20) DEFAULT NULL COMMENT 'mongodb配置表id',
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `delete_flag` tinyint(1) DEFAULT '0' COMMENT '删除标识-0: 未删除 1-已删除',
  `create_user` varchar(255) DEFAULT NULL COMMENT '创建人',
  `update_user` varchar(255) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`),
  KEY `idx_system_info_id` (`system_info_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='代码生成基础信息表';
CREATE TABLE `lowcode_sentinel_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `sentinel_name` varchar(255) DEFAULT NULL COMMENT 'sentinel名称',
  `console_url` varchar(255) DEFAULT NULL COMMENT '控制台地址',
  `zk_url` varchar(255) DEFAULT NULL COMMENT 'zk地址',
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_user` varchar(255) DEFAULT NULL COMMENT '创建人',
  `delete_flag` tinyint(1) DEFAULT '0' COMMENT '删除标识-0: 未删除 1-已删除',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `update_user` varchar(255) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='代码生成-sentinel配置信息表';
CREATE TABLE `lowcode_sys_dict_data` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，自增长',
  `type_id` bigint(20) DEFAULT NULL COMMENT '数据字典类型id',
  `code` varchar(128) DEFAULT NULL COMMENT '字典code',
  `value` varchar(128) DEFAULT NULL COMMENT '字典值',
  `status` tinyint(1) DEFAULT '1' COMMENT '状态 0:禁用 1:启用 ',
  `show_no` int(11) DEFAULT NULL COMMENT '排序',
  `remark` varchar(128) DEFAULT NULL COMMENT '备注 ',
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_user` varchar(255) DEFAULT NULL COMMENT '创建人',
  `delete_flag` tinyint(1) DEFAULT '0' COMMENT '删除标识-0: 未删除 1-已删除',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `update_user` varchar(255) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`),
  KEY `idx_type_id` (`type_id`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='低代码平台-数据字典数据表';
CREATE TABLE `lowcode_sys_dict_type` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，自增长',
  `type_name` varchar(128) DEFAULT NULL COMMENT '类型名称',
  `type_code` varchar(128) DEFAULT NULL COMMENT '类型编码',
  `type_source` tinyint(1) DEFAULT '1' COMMENT '来源 1:固定 2:接口',
  `request_url` varchar(128) DEFAULT NULL COMMENT '请求url',
  `request_type` varchar(8) DEFAULT NULL COMMENT '请求方式 get post',
  `request_params` varchar(2000) DEFAULT NULL COMMENT '请求参数 ',
  `request_name` varchar(128) DEFAULT NULL COMMENT '请求字段名称',
  `request_code` varchar(128) DEFAULT NULL COMMENT '请求字段编码',
  `status` tinyint(1) DEFAULT '1' COMMENT '状态 0:禁用 1:启用 ',
  `show_no` int(11) DEFAULT NULL COMMENT '排序',
  `remark` varchar(128) DEFAULT NULL COMMENT '备注 ',
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_user` varchar(255) DEFAULT NULL COMMENT '创建人',
  `delete_flag` tinyint(1) DEFAULT '0' COMMENT '删除标识-0: 未删除 1-已删除',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `update_user` varchar(255) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='低代码平台-数据字典类型表';
CREATE TABLE `lowcode_system_db_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `db_driver` varchar(50) NOT NULL COMMENT '数据库驱动类型',
  `db_host` varchar(100) NOT NULL COMMENT '数据库host',
  `db_port` varchar(100) NOT NULL COMMENT '数据库port',
  `db_url` varchar(500) NOT NULL COMMENT '数据库连接url',
  `db_username` varchar(100) NOT NULL COMMENT '账户',
  `db_password` varchar(100) NOT NULL COMMENT '密码',
  `db_name` varchar(100) NOT NULL COMMENT '数据库名',
  `db_desc` varchar(200) NOT NULL DEFAULT '' COMMENT '数据库描述用于展示',
  `create_user` varchar(40) NOT NULL DEFAULT 'SYSTEM' COMMENT '创建人',
  `create_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_user` varchar(40) NOT NULL DEFAULT 'SYSTEM' COMMENT '更新人',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  KEY `idx_cgud_dbname` (`db_name`),
  KEY `idx_cgud_dhost` (`db_host`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPACT COMMENT='数据库信息';
CREATE TABLE `lowcode_system_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `system_code` varchar(50) DEFAULT NULL COMMENT '系统编码/artifactId',
  `package_name` varchar(100) DEFAULT NULL COMMENT '工程包名',
  `context_path` varchar(50) DEFAULT NULL COMMENT '工程访问前缀',
  `group_id` varchar(50) DEFAULT NULL COMMENT '打包包名',
  `artifact_id` varchar(100) DEFAULT NULL,
  `version` varchar(20) DEFAULT '1.0.0' COMMENT '版本号',
  `system_name` varchar(255) DEFAULT NULL COMMENT '系统名称',
  `system_desc` varchar(2048) DEFAULT NULL COMMENT '系统描述信息',
  `team_name` varchar(255) DEFAULT NULL COMMENT '系统维护的团队',
  `leader` varchar(255) DEFAULT NULL COMMENT '系统负责人',
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_flag` tinyint(1) DEFAULT '0' COMMENT '删除标识-0: 未删除 1-已删除',
  `create_user` varchar(255) DEFAULT NULL COMMENT '创建人',
  `update_user` varchar(255) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='工程信息表';
CREATE TABLE `lowcode_template_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '模板编码',
  `template_name` varchar(100) DEFAULT NULL COMMENT '模板名称',
  `template_desc` varchar(200) DEFAULT NULL COMMENT '模板描述',
  `template_type` tinyint(1) DEFAULT NULL COMMENT '模板类型 1.应用层；2.微服务层；3.前端',
  `plugins` text COMMENT '包含组件(多个使用#分隔)，例如service#manager#repostiroy',
  `middleware` text COMMENT '中间件(多个使用#分隔),比如redis#kafka',
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_flag` tinyint(1) DEFAULT '0' COMMENT '删除标识-0: 未删除 1-已删除',
  `create_user` varchar(255) DEFAULT NULL COMMENT '创建人',
  `update_user` varchar(255) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='工程模板信息表';CREATE TABLE `lowcode_user_day_stat_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `emp_no` varchar(20) DEFAULT NULL COMMENT '员工工号',
  `emp_name` varchar(50) DEFAULT NULL COMMENT '员工名字',
  `use_system_num` int(11) DEFAULT NULL COMMENT '接入系统数',
  `code_total_num` bigint(20) DEFAULT NULL COMMENT '代码生产量(行)',
  `team_name` varchar(255) DEFAULT NULL COMMENT '团队名字',
  `start_date` datetime DEFAULT NULL COMMENT '开始时间',
  `end_date` datetime DEFAULT NULL COMMENT '结束时间',
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `delete_flag` tinyint(1) DEFAULT '0' COMMENT '删除标识-0: 未删除 1-已删除',
  `create_user` varchar(255) DEFAULT NULL COMMENT '创建人',
  `update_user` varchar(255) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户统计报表';

CREATE TABLE `lowcode_user_total_stat_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `emp_no` varchar(20) DEFAULT NULL COMMENT '员工工号',
  `emp_name` varchar(50) DEFAULT NULL COMMENT '员工名字',
  `use_system_num` int(11) DEFAULT NULL COMMENT '接入系统数',
  `code_total_num` bigint(20) DEFAULT NULL COMMENT '代码生产量(行)',
  `team_name` varchar(255) DEFAULT NULL COMMENT '团队名字',
  `visit_times` int(11) DEFAULT NULL COMMENT '访问次数',
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `delete_flag` tinyint(1) DEFAULT '0' COMMENT '删除标识-0: 未删除 1-已删除',
  `create_user` varchar(255) DEFAULT NULL COMMENT '创建人',
  `update_user` varchar(255) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户累计统计信息';